config/routes.rb
WebStock::Application.routes.draw do
  resources :scraping_webs

  root to: 'webs#index'
  resources :webs
  get "chart", :controller => :webs, :action => :chart

end

app/models/scraping_web.rb
class ScrapingWeb < ActiveRecord::Base
	belongs_to :web
end

app/models/web.rb
class Web < ActiveRecord::Base
	has_many :scraping_web
	#paginates_per 50
#scope :name_is, lambda {|name|where("login like ?", "%#{name}%")}
#scope :url_is, lambda {|url|where("name like ?", "%#{url}%")}


end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scraping_webs_controller.rb
class ScrapingWebsController < ApplicationController
  before_action :set_scraping_web, only: [:show, :edit, :update, :destroy]

  # GET /scraping_webs
  # GET /scraping_webs.json
  def index
    @scraping_webs = ScrapingWeb.all
  end

  # GET /scraping_webs/1
  # GET /scraping_webs/1.json
  def show
  end

  # GET /scraping_webs/new
  def new
    @scraping_web = ScrapingWeb.new
  end

  # GET /scraping_webs/1/edit
  def edit
  end

  # POST /scraping_webs
  # POST /scraping_webs.json
  def create
    @scraping_web = ScrapingWeb.new(scraping_web_params)

    respond_to do |format|
      if @scraping_web.save
        format.html { redirect_to @scraping_web, notice: 'Scraping web was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scraping_web }
      else
        format.html { render action: 'new' }
        format.json { render json: @scraping_web.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scraping_webs/1
  # PATCH/PUT /scraping_webs/1.json
  def update
    respond_to do |format|
      if @scraping_web.update(scraping_web_params)
        format.html { redirect_to @scraping_web, notice: 'Scraping web was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scraping_web.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scraping_webs/1
  # DELETE /scraping_webs/1.json
  def destroy
    @scraping_web.destroy
    respond_to do |format|
      format.html { redirect_to scraping_webs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scraping_web
      @scraping_web = ScrapingWeb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scraping_web_params
      params.require(:scraping_web).permit(:name, :url, :html, :facebook, :twitter, :hatena, :deleted_at, :timing)
    end
end

app/controllers/webs_controller.rb
class WebsController < ApplicationController
  before_action :set_web, only: [:show, :edit, :update, :destroy]

  # GET /webs
  # GET /webs.json
  
  def chart
    respond_to do |format|
      format.html
    end
  end
  def search
    @search = Web.all    
  end

  def index
    @webs = Web.all
    #@webs = Web.order(:created).page params[:page]
  end

  # GET /webs/1
  # GET /webs/1.json
  def show
  end

  # GET /webs/new
  def new
    @web = Web.new
  end

  # GET /webs/1/edit
  def edit
  end

  # POST /webs
  # POST /webs.json
  def create

    @web = Web.new(web_params)

    respond_to do |format|
      if @web.save
        format.html { redirect_to @web, notice: 'Web was successfully created.' }
        format.json { render action: 'show', status: :created, location: @web }
      else
        format.html { render action: 'new' }
        format.json { render json: @web.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webs/1
  # PATCH/PUT /webs/1.json
  def update
    respond_to do |format|
      if @web.update(web_params)
        format.html { redirect_to @web, notice: 'Web was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @web.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webs/1
  # DELETE /webs/1.json
  def destroy
    @web.destroy
    respond_to do |format|
      format.html { redirect_to webs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_web
      @web = Web.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def web_params
      params.require(:web).permit(:name, :url, :html, :facebook, :twitter, :hatena, :deleted_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scraping_webs_helper.rb
module ScrapingWebsHelper
end

app/helpers/webs_helper.rb
module WebsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WebStock" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">WebStock</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "マスター", "/path1"  %></li>
              <li><%= link_to "スクレイピング", "/path2"  %></li>
              <li><%= link_to "使い方", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Markezin", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/scraping_webs/_form.html.erb
<%= form_for(@scraping_web) do |f| %>
  <% if @scraping_web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scraping_web.errors.count, "error") %> prohibited this scraping_web from being saved:</h2>

      <ul>
      <% @scraping_web.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :html %><br>
    <%= f.text_area :html %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.number_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.number_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :hatena %><br>
    <%= f.number_field :hatena %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br>
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="field">
    <%= f.label :timing %><br>
    <%= f.number_field :timing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scraping_webs/edit.html.erb
<h1>Editing scraping_web</h1>

<%= render 'form' %>

<%= link_to 'Show', @scraping_web %> |
<%= link_to 'Back', scraping_webs_path %>

app/views/scraping_webs/index.html.erb
<h1>Listing scraping_webs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Html</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th>Hatena</th>
      <th>Deleted at</th>
      <th>Timing</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scraping_webs.each do |scraping_web| %>
      <tr>
        <td><%#= scraping_web.name %></td>
        <td><%= scraping_web.url %></td>
        <td><%#= scraping_web.html %></td>
        <td><%= scraping_web.facebook %></td>
        <td><%= scraping_web.twitter %></td>
        <td><%= scraping_web.hatena %></td>
        <td><%= scraping_web.created_at %></td>
        <td><%= scraping_web.timing %></td>
        <td><%= link_to 'Show', scraping_web %></td>
        <td><%= link_to 'Edit', edit_scraping_web_path(scraping_web) %></td>
        <td><%= link_to 'Destroy', scraping_web, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scraping web', new_scraping_web_path %>

app/views/scraping_webs/new.html.erb
<h1>New scraping_web</h1>

<%= render 'form' %>

<%= link_to 'Back', scraping_webs_path %>

app/views/scraping_webs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scraping_web.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @scraping_web.url %>
</p>

<p>
  <strong>Html:</strong>
  <%= @scraping_web.html %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @scraping_web.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @scraping_web.twitter %>
</p>

<p>
  <strong>Hatena:</strong>
  <%= @scraping_web.hatena %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @scraping_web.deleted_at %>
</p>

<p>
  <strong>Timing:</strong>
  <%= @scraping_web.timing %>
</p>

<%= link_to 'Edit', edit_scraping_web_path(@scraping_web) %> |
<%= link_to 'Back', scraping_webs_path %>

app/views/webs/_form.html.erb
<%= form_for(@web) do |f| %>
  <% if @web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web.errors.count, "error") %> prohibited this web from being saved:</h2>

      <ul>
      <% @web.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div> -->
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url,:id => "url"%>
  </div>

<!--   <div class="field">
    <%= f.label :html %><br>
    <%= f.text_area :html,:id => "source" %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.number_field :facebook,:id => "facebook" %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.number_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :hatena %><br>
    <%= f.number_field :hatena %>
  </div>
  <div class="field">
    <%= f.label :hatena %><br>
    <%= f.number_field :hatena %>
  </div> -->
  <div class="field">
    <%= f.label :データ取得タイミング %><br>
    <%#= f.select:timing, options_for_select({"取得しない" => "0","１分" => "1", "5分" => "2", "10分" => "3", "30分" => "4", "1時間" => "5", "１日" => "6"}) %>
    <%= f.select :timing, [["取得しない", 0], ["1分", 1]],  :prompt => "選択してください" %>
    <%#= f.radio_box :timing, :tag_value %>

   

  </div>

 
  <div class="actions">
    <%= f.submit("登録", :confirm => "登録してよろしいでしょうか？") %>
  </div>


<% end %>

<!-- <button onclick="frame_load();">リンク先をiframeに表示する</button> -->

app/views/webs/chart.html.erb
<!-- <%= javascript_tag do %>
  window.your_object = <%= raw @your_object.to_json %>;
<% end %>
 -->



<script>
var dataset = [
	[   5,   150 ],
	[ 480,   300 ],
	[ 250,   400 ],
	[ 100,   330 ],
	[ 330,   50 ],
	[ 410,   120 ],
	[ 475,   340 ],
	[  25,   470 ],
	[  85,   210 ],
	[ 220,   380 ]];
 
var svg = d3.select("body")
		.append("svg")
		.attr("width", 1000)
		.attr("height", 1000);
 
svg.selectAll("circle")
	.data(dataset)
	.enter()
	.append("circle")
	.attr({
		cx : function(d) {return d[0] + 50},
		cy : function(d) {return 500 - d[1]},
		r : function(d) {return 10},
		fill : "red"
	})
 
</script>

app/views/webs/edit.html.erb
<h1>Editing web</h1>

<%= render 'form' %>

<%= link_to 'Show', @web %> |
<%= link_to 'Back', webs_path %>

app/views/webs/index.html.erb
<h1></h1>
<%= link_to '新規作成', new_web_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th>Hatena</th>
      <th>取得タイミング</th>
    </tr>
  </thead>

  <tbody>
    <% @webs.each do |web| %>
      <tr>
        <td><%= web.name %></td>
        <td><%= web.url %></td>
        <td><%= web.facebook %></td>
        <td><%= web.twitter %></td>
        <td><%= web.hatena %></td>
        <td><%= web.timing %></td>
        <td><%= link_to '詳細', web %></td>
        <td><%= link_to '編集', edit_web_path(web) %></td>
        <td><%= link_to '削除', web, method: :delete, data: { confirm: '本当に削除してよろしいでしょうか？' } %></td>
      </tr>
    <% end %>
    <%#= paginate @webs %>
  </tbody>
</table>

<br>

app/views/webs/new.html.erb
<h1>New web</h1>

<%= render 'form' %>

<%= link_to 'Back', webs_path %>

app/views/webs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @web.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @web.url %>
</p>

<p>
  <strong>Html:</strong>
  <%= @web.html %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @web.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @web.twitter %>
</p>

<p>
  <strong>Hatena:</strong>
  <%= @web.hatena %>
</p>

<p>
  <strong>timing:</strong>
  <%= @web.timing %>
</p>


<%= link_to 'Edit', edit_web_path(@web) %> |
<%= link_to 'Back', webs_path %>